// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

type Job struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Country      string `json:"country"`
	Description  string `json:"description"`
	IsDeleted    bool   `json:"isDeleted"`
	NoOfPosition int    `json:"noOfPosition"`
	CreatedAt    string `json:"createdAt"`
	CreatedBy    string `json:"createdBy"`
}

type NewJob struct {
	Name         string `json:"name"`
	Country      string `json:"country"`
	Description  string `json:"description"`
	IsDeleted    bool   `json:"isDeleted"`
	NoOfPosition int    `json:"noOfPosition"`
}
